name: "Stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue is stale because it has been open for some time with no activity."
        stale-issue-label: "stale"
        days-before-issue-stale: 730
        days-before-issue-close: -1
        remove-issue-stale-when-updated: false
        debug-only: true
